version: 0.2

phases:
  install:
    runtime-versions:
        ruby: 2.6
    commands:
      - aws eks update-kubeconfig --name $CLUSTER
      - aws ecr get-login --region us-west-2 --no-include-email | bash
      - wget -q https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
      - wget -q https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz.sha256
      - if [[ "$(cat helm-v2.14.3-linux-amd64.tar.gz.sha256)" != "$(sha256sum helm-v2.14.3-linux-amd64.tar.gz | awk '{print $1}')" ]] ; then echo "There was a problem downloading Helm && exit 1" ; fi
      - tar xvf helm-v2.14.3-linux-amd64.tar.gz

  pre_build:
    commands:
      - git clone -q https://github.com/discourse/discourse_docker.git
      - cd discourse_docker
      - git checkout 86b9032bbe75cfd11476c44a5c62f8882dd8ad97
      - mkdir -p includes && mkdir -p containers
      - mv ../discourse-$ENV.yml containers/app.yml
      - mv ../includes/* includes/
      
      # Overwrites
      - sed -i "s,environment,$ENV," includes/after_build.yml
      - sed -i "s,code-revision,$CODE_REVISION," containers/app.yml

  build:
    commands:
      - ./launcher bootstrap app
      - cd ..
  post_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - export DOCKER_REVISION=`echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7`-`date +%s`
      - echo $DOCKER_REVISION
      - docker tag local_discourse/app:latest "$ECR:$ENV-$DOCKER_REVISION"
      - docker push "$ECR:$ENV-$DOCKER_REVISION"
      - linux-amd64/helm template -f "k8s/values/$ENV.yaml" --set docker_registry="$ECR",revision="$ENV-$DOCKER_REVISION" k8s/ | kubectl apply -f -
