apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  DISCOURSE_DEVELOPER_EMAILS: 'lmcardle@mozilla.com, alberto@mozilla.com'
  LANG: 'en_US.UTF-8'
  DISCOURSE_DB_USERNAME: 'discourse'
  DISCOURSE_DB_NAME: 'discourse'
  DISCOURSE_DB_PORT: '5432'
  DISCOURSE_DB_SOCKET: ''
  DISCOURSE_SMTP_PORT: '587'
  DISCOURSE_SMTP_ADDRESS: 'email-smtp.us-west-2.amazonaws.com'
  DISCOURSE_HOSTNAME: {{ .Values.domain_name }}
  DISCOURSE_CDN_URL: {{ .Values.cdn_url }}
  DISCOURSE_AUTH0_DOMAIN: 'auth.mozilla.auth0.com'
  DISCOURSE_AUTH0_CALLBACK_URL: {{ .Values.auth0_callback_url }}
  DISCOURSE_S3_REGION: 'us-west-2'
  DISCOURSE_S3_USE_IAM_PROFILE: 'true'
  DISCOURSE_ENABLE_S3_UPLOADS: true
  PG_MAJOR: 12

  # Login
  DISCOURSE_ENABLE_LOCAL_LOGINS: false

  # Security
  DISCOURSE_FORCE_HTTPS: true
  DISCOURSE_CONTENT_SECURITY_POLICY: false # we handle this in headers.yml
  DISCOURSE_ENABLE_CORS: 'true'

  # Email
  DISCOURSE_MANUAL_POLLING_ENABLED: true
  DISCOURSE_EMAIL_IN: true
  DISCOURSE_REPLY_BY_EMAIL_ENABLED: true
  DISCOURSE_AUTO_EMAIL_IN_ENABLED: true
  DISCOURSE_AUTO_EMAIL_IN_DIVIDER: "."
  DISCOURSE_AUTO_EMAIL_IN_APPEND: true
  DISCOURSE_EMAIL_IN_AUTHSERV_ID: "amazonses.com"
  DISCOURSE_REPLY_BY_EMAIL_ADDRESS: replies+%{reply_key}@{{ .Values.email_domain }}
  DISCOURSE_NOTIFICATION_EMAIL: notifications@{{ .Values.email_domain }}
  DISCOURSE_AUTO_EMAIL_IN_DOMAIN: {{ .Values.email_domain }}

  # Ruby
  RUBY_GLOBAL_METHOD_CACHE_SIZE: '131072'
  RUBY_GC_HEAP_GROWTH_MAX_SLOTS: '40000'
  RUBY_GC_HEAP_INIT_SLOTS: '400000'
  RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: '1.5'
  RAILS_ENV: 'production'
  UNICORN_SIDEKIQS: '1'
  UNICORN_WORKERS: '1'
  DISCOURSE_LOG_SIDEKIQ: 1
  DISCOURSE_LOG_SIDEKIQ_INTERVAL: 1
