apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    k8s-app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      k8s-app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        k8s-app: {{ .Values.name }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.arn_role }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.docker_registry }}:{{ .Values.revision }}
          imagePullPolicy: Always
          command: ['/sbin/boot']
          resources:
            requests:
              memory: {{ .Values.memory_req }}
              cpu: {{ .Values.cpu_req }}
            limits:
              memory: {{ .Values.memory_limit }}
              cpu: {{ .Values.cpu_limit }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
          - configMapRef:
              name: {{ .Values.name }}
          - secretRef:
              name: {{ .Values.name }}
          volumeMounts:
          - mountPath: /shared/log
            name: logs
          livenessProbe:
            httpGet:
              path: /srv/status
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
        - name: logger
          image: alpine:latest
          command:
          - /bin/sh
          - -c
          args:
          - sleep 60 && tail -f /logs/rails/production.log
          resources:
            limits:
              memory: 128Mi
              cpu: 200m
            requests:
              memory: 64Mi
              cpu: 50m
          volumeMounts:
          - mountPath: /logs
            name: logs
        - image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/remote_syslog2:0.2
          name: remote-logger
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
          - name: logs
            mountPath: /logs
          - name: remote-logger
            mountPath: /etc/rs2
      volumes:
      - emptyDir: {}
        name: logs
      - name: remote-logger
        secret:
          secretName: logger-secret
